apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-app
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-app
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This repository provides a foundational configuration to build and operate a Ghost blogging application, including handling its dependencies and configurations. The setup ensures a streamlined and repeatable deployment in a cloud environment.

    meta.crossplane.io/readme: |
     This repository offers a specialized configuration for deploying and managing the Ghost blogging application on Kubernetes using Crossplane. This setup provides the necessary infrastructure to deploy Ghost with with helm and managed with Crossplane in Kubernetes. This approach ensures a flexible, streamlined deployment to any cloud provider.

     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-app).
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-helm
      version: "v0.19.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.4.0"
